// src/components/layout/AppFooter.vue
<template>
  <footer class="bg-black text-gold text-center py-4">
    <div class="container">
      <p class="mb-0 text-gold">
        &copy; 2024 Portfolio. Master Supakon Karanyawad
      </p>
      <p class="mb-0">
        This portfolio uses <span class="text-gold">Framework </span><span class="text-red"> Vue.js <span class="text-gold">&amp;</span> Sanity</span><span class="text-gold"> Headless CMS</span>
      </p>
    </div>
  </footer>
</template>

<script setup>
defineOptions({
  name: 'AppFooter'
});
</script>

// src/components/layout/AppFooter.jsx
export default function AppFooter() {
  return (
    <footer className="bg-black text-gold text-center py-4">
      <div className="container">
        <p className="mb-0 text-gold">
          &copy; 2026 Portfolio. Master Supakon Karanyawad
        </p>
        <p className="mb-0">
          This portfolio uses <span className="text-gold">Framework </span>
          <span className="text-red">
            React <span className="text-gold">&amp;</span> Sanity
          </span>
          <span className="text-gold"> Headless CMS</span>
        </p>
      </div>
    </footer>
  );
}
