// src/components/layout/AppHeader.vue
<template>
  <header class="text-gold flex justify-center items-center min-h-screen bg-black p-0 m-0">
    <div class="container flex flex-col items-center">
      <div class="text-center">
        <img
          src="@/assets/foto/logo2.png"
          alt="Logo"
          class="max-h-[250px] mx-auto"
        >
      </div>
    </div>
  </header>
</template>

<script setup>
defineOptions({
  name: "AppHeader"
});
</script>

// src/components/layout/AppHeader.jsx
import logo from "@/assets/foto/logo2.png";

export default function AppHeader() {
  return (
    <header className="text-gold flex justify-center items-center min-h-screen bg-black p-0 m-0">
      <div className="container flex flex-col items-center">
        <div className="text-center">
          <img src={logo} alt="Logo" className="max-h-[250px] mx-auto" />
        </div>
      </div>
    </header>
  );
}
