// src/views/HomePage.jsx
import profilePhoto from "@/assets/foto/optimized/get.jpeg";

export default function HomePage() {
  return (
    <div className="container">
      <div className="flex flex-col items-center justify-center min-h-[80vh] text-center px-lg py-xxl md:min-h-[70vh] md:px-md md:py-lg">
        <div className="max-w-[800px] mx-auto">
          <h1 className="page-title animate-fade-in">
            <span className="text-red font-bold inline-block animate-bounce-slow">Nice</span> to meet you! &#x1F601;
          </h1>
          <h2 className="animate-fade-in-slow text-gold opacity-90 text-xl">
            Hi, My name is Master Supakon Karanyawad
          </h2>
          <h2 className="animate-fade-in-slow text-gold mb-xl opacity-90 text-xl">
            but you can call me <span className="text-red font-bold">Get &#x1F680;</span>
          </h2>

          <img src={profilePhoto} alt="Master Supakon" className="h-auto mx-auto" />

          <div className="animate-fade-in-slower text-lg mb-xl leading-relaxed">
            <p className="text-white">
              Based in the <span className="text-gold">Netherlands</span>, I&apos;m a{" "}
              <span className="text-red">front end developer</span> &#x1F4BB;
            </p>
          </div>

          <div className="animate-fade-in-slowest flex items-center justify-center gap-lg">
            <a
              href="https://www.linkedin.com/in/get-ms-karanyawad"
              target="_blank"
              rel="noopener noreferrer"
              className="social-icon social-icon-large"
              aria-label="LinkedIn Profile"
            >
              <i className="bi bi-linkedin" />
            </a>
            <a
              href="https://github.com/Thaiseboy/Hi-"
              target="_blank"
              rel="noopener noreferrer"
              className="social-icon social-icon-large"
              aria-label="GitHub Profile"
            >
              <i className="bi bi-github" />
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/views/HomePage.vue
<template>
  <div class="container">
    <div class="flex flex-col items-center justify-center min-h-[80vh] text-center px-lg py-xxl md:min-h-[70vh] md:px-md md:py-lg">
      <div class="max-w-[800px] mx-auto">
        <h1 class="page-title animate-fade-in">
          <span class="text-red font-bold inline-block animate-bounce-slow">Nice</span> to meet you! &#x1F601;
        </h1>
        <h2 class="animate-fade-in-slow text-gold opacity-90 text-xl">
          Hi, My name is Master Supakon Karanyawad
        </h2>
        <h2 class="animate-fade-in-slow text-gold mb-xl opacity-90 text-xl">
          but you can call me
          <span class="text-red font-bold">Get &#x1F680;</span>
        </h2>

        <img
          src="@/assets/foto/optimized/get.jpeg"
          alt="Master Supakon"
          class=" h-auto mx-auto "
        />

        <div class="animate-fade-in-slower text-lg mb-xl leading-relaxed">
          <p class="text-white">
            Based in the <span class="text-gold">Netherlands</span>, I'm a
            <span class="text-red">front end developer</span> &#x1F4BB;
          </p>
        </div>

        <div class="animate-fade-in-slowest flex items-center justify-center gap-lg">
          <a
            href="https://www.linkedin.com/in/get-ms-karanyawad"
            target="_blank"
            class="social-icon social-icon-large"
            aria-label="LinkedIn Profile"
          >
            <i class="bi bi-linkedin" />
          </a>
          <a
            href="https://github.com/Thaiseboy/Hi-"
            target="_blank"
            class="social-icon social-icon-large"
            aria-label="GitHub Profile"
          >
            <i class="bi bi-github" />
          </a>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
defineOptions({
  name: "HomePage"
});
</script>

<style scoped>
.social-icon::after {
  content: '';
  position: absolute;
  bottom: -8px;
  left: 50%;
  transform: translateX(-50%);
  width: 0;
  height: 3px;
  background-color: var(--color-secondary);
  transition: width 0.3s ease;
}

.social-icon:hover::after {
  width: 100%;
}
</style>
